<a href="https://colab.research.google.com/github/sruthi1996/homework_0-/blob/master/numpyarrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Understanding Numpy package:
To work with matrices, we have a matrix matlib library that returns matrices instead of a n-dimensional array 

In [0]:
import numpy as np
import numpy.matlib


In [0]:
a = np.array([1,2,3])
b = np.array([4,5,6])
a+b

array([5, 7, 9])

In [0]:
b%1
#returns the reaminder


array([0, 0, 0])

In [0]:
ar =np.array([[2,3,4],[5,6,7]])
print("shape and size of the array:", ar.shape,",", ar.size)

shape and size of the array: (2, 3) , 6


In [0]:
print("The elements in the array are of type:", ar.dtype)

The elements in the array are of type: int64


Array Broadcasting

Array broadcasting is done when we need to carry out binary operations on multi-sized arrays.

In [0]:
Ab = np.ones((3, 3))
print(Ab)

In [0]:
a=np.array([1,2,3])
print(Ab + a)

[[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]


In [0]:
M = np.ones((2, 3))
a = np.arange(3)
print(M,a)


[[1. 1. 1.]
 [1. 1. 1.]] [0 1 2]


In [0]:
a1 = np.arange(3).reshape((3, 1))
b1 = np.arange(3)
print(a1,b1)

[[0]
 [1]
 [2]] [0 1 2]


In [0]:
M = np.ones((3, 2))
a = np.arange(3)
print(M)
print(a)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
[0 1 2]


In [0]:
X = np.random.random((10, 3))
print(X)

[[0.51084199 0.97703066 0.81253808]
 [0.50487656 0.50311169 0.53203419]
 [0.02972363 0.20589586 0.28388658]
 [0.04481214 0.20252703 0.58292405]
 [0.51643769 0.73331485 0.98455219]
 [0.85863738 0.22472542 0.80596499]
 [0.81171153 0.53938393 0.81208116]
 [0.99600358 0.63580498 0.74546216]
 [0.94677257 0.27333363 0.01325911]
 [0.5064822  0.54813229 0.2989646 ]]


In [0]:
#To compute the mean of the each of the elements of the array

In [0]:
X_mean = X.mean(0)
X_mean

array([0.57262993, 0.48432603, 0.58716671])

In [0]:
X_centered = X - X_mean
X_centered

array([[-0.06178794,  0.49270462,  0.22537137],
       [-0.06775336,  0.01878565, -0.05513252],
       [-0.5429063 , -0.27843017, -0.30328013],
       [-0.52781778, -0.281799  , -0.00424266],
       [-0.05619224,  0.24898881,  0.39738547],
       [ 0.28600745, -0.25960061,  0.21879828],
       [ 0.2390816 ,  0.0550579 ,  0.22491445],
       [ 0.42337365,  0.15147894,  0.15829545],
       [ 0.37414265, -0.2109924 , -0.5739076 ],
       [-0.06614773,  0.06380626, -0.28820211]])

In [0]:
#To represent an n-dimensional array as a matrix or viceversa
import numpy.matlib 
import numpy as np  

i = np.matrix('1,2;3,4;5,6;7,8') 
print(i) 

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [0]:
#To generate the maximum and minimum elements of an ndarray; a matrix
ar1 = np.array([[1, 5, 6], 
                [4, 7, 2], 
                [3, 1, 9]]) 
print ("Largest element in the matrix is:", ar1.max()) 
print ("Largest element from each of the row is:", 
                    ar1.max(axis = 1))  

Largest element in the matrix is: 9
Largest element from each of the row is: [6 7 9]


In [0]:
#similarily printing minimum element of a matrix using numpy:
print ("Least element of each of the columns in the matrix:", 
                        arr.min(axis = 0)) 

Least element of each of the columns in the matrix: [1 1 2]


In [0]:
#To print the sum
print ("Sum of all elements in array :", 
                            arr.sum()) 

Sum of all elements in array : 38


In [0]:
#To perform binary operations on the nd arrays or matrices:
a1 = np.array([[10, 20], 
            [30, 40]]) 
a2 = np.array([[40, 30], 
            [20, 10]]) 
print ("Array sum:\n", a1 + a2) 

print ("\nArray multiplication:\n", a1*a2)

print ("\nMatrix multiplication:\n", a1.dot(a2))

Array sum:
 [[50 50]
 [50 50]]

Array multiplication:
 [[400 600]
 [600 400]]

Matrix multiplication:
 [[ 800  500]
 [2000 1300]]
